name: equip_check_client
version: 1.0.4+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  crypto: ^3.0.3
  intl: ^0.18.1
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  sensors_plus: ^4.0.0
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.9.0
  image: ^4.1.7
  flutter_native_splash: ^2.4.0
  gal: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_keyboard_visibility: ^6.0.0
  connectivity_plus: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  permission_handler: ^11.3.1
  assets_audio_player: ^3.1.1
  device_info_plus: ^9.0.0
  package_info_plus: ^5.0.0
  url_launcher: ^6.2.5
  flutter_dotenv: ^5.1.0
  


dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter
  retrofit_generator: '>=7.0.0 <8.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1


flutter: 
  uses-material-design: true
  assets:
    - assets/audios/
    - .env
